In [1]:
#!pip install --upgrade pip
!pip install gym

import gym

import numpy as np 
import time, math, random
from typing import Tuple

In [4]:
# 1. It renders instance for 1000 timesteps, perform random actions
import gym

env = gym.make('CartPole-v0')
env.reset()
for _ in range(500):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()
# 2. To check all env available, uninstalled ones are also shown
from gym import envs 
print(envs.registry.all())

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v3), EnvSpec(BipedalWalkerHardcore-v3), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v0), EnvSpec(FrozenLake8x8-v0), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v3), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(HalfCheetah-v3), EnvSpec(Hopper-v2), EnvSpec(Hopper-v3), EnvSpec(Swimmer-v2), EnvSp

## 아래는 최신 코드

In [2]:
import gym
import time

env = gym.make('CartPole-v1') #강화학습 환경 불러오기

for i_episode in range(20):
    # 새로운 에피소드(initial environment)를 불러온다(reset)
    observation = env.reset()
    for t in range(100):
        env.render() #화면에 출력 / 행동 취하기 이전 환경에서 얻은 관찰값(obsevation)적용해서 그림
        time.sleep(0.05)

        # 행동(action)을 취하기 이전에 환경에 대해 얻은 관찰값(observation)
        print('observation before action:')
        print(observation)
        action = env.action_space.sample()#임의의 action 선택
        observation, reward, done, info = env.step(action)#선택한 action을 환경으로 보냄
        time.sleep(0.05)

        # 행동(action)을 취한 이후에 환경에 대해 얻은 관찰값(observation)
        print('observation after action:')
        print(observation)

        if done:
            print("Episode finished after {} timesteps".format(t+1))
         
            break
            
env.close()

observation before action:
[0.04424914 0.02500292 0.04109852 0.00070651]
observation after action:
[ 0.0447492  -0.17068361  0.04111265  0.306068  ]
observation before action:
[ 0.0447492  -0.17068361  0.04111265  0.306068  ]
observation after action:
[0.04133553 0.02382911 0.04723401 0.02662919]
observation before action:
[0.04133553 0.02382911 0.04723401 0.02662919]
observation after action:
[ 0.04181211 -0.17193727  0.04776659  0.33383289]
observation before action:
[ 0.04181211 -0.17193727  0.04776659  0.33383289]
observation after action:
[0.03837336 0.02247343 0.05444325 0.05658748]
observation before action:
[0.03837336 0.02247343 0.05444325 0.05658748]
observation after action:
[ 0.03882283 -0.17338516  0.055575    0.36593849]
observation before action:
[ 0.03882283 -0.17338516  0.055575    0.36593849]
observation after action:
[ 0.03535513 -0.36925103  0.06289377  0.67561433]
observation before action:
[ 0.03535513 -0.36925103  0.06289377  0.67561433]
observation after action:

observation before action:
[0.35214694 0.0047582  0.02312349 0.44727228]
observation after action:
[0.3522421  0.19954554 0.03206893 0.16196708]
observation before action:
[0.3522421  0.19954554 0.03206893 0.16196708]
observation after action:
[0.35623302 0.00397952 0.03530828 0.46459193]
observation before action:
[0.35623302 0.00397952 0.03530828 0.46459193]
observation after action:
[0.35631261 0.19858521 0.04460012 0.18324381]
observation before action:
[0.35631261 0.19858521 0.04460012 0.18324381]
observation after action:
[0.36028431 0.0028544  0.04826499 0.48965615]
observation before action:
[0.36028431 0.0028544  0.04826499 0.48965615]
observation after action:
[0.3603414  0.19726341 0.05805811 0.21256663]
observation before action:
[0.3603414  0.19726341 0.05805811 0.21256663]
observation after action:
[0.36428667 0.00136151 0.06230945 0.52298386]
observation before action:
[0.36428667 0.00136151 0.06230945 0.52298386]
observation after action:
[ 0.3643139  -0.19457953  0.072

observation before action:
[-0.01820953 -0.02135929 -0.00028107 -0.09258233]
observation after action:
[-0.01863672 -0.21647721 -0.00213272  0.20001191]
observation before action:
[-0.01863672 -0.21647721 -0.00213272  0.20001191]
observation after action:
[-0.02296626 -0.02132482  0.00186752 -0.09334303]
observation before action:
[-0.02296626 -0.02132482  0.00186752 -0.09334303]
observation after action:
[-2.33927602e-02  1.73770311e-01  6.56705012e-07 -3.85436174e-01]
observation before action:
[-2.33927602e-02  1.73770311e-01  6.56705012e-07 -3.85436174e-01]
observation after action:
[-0.01991735 -0.02135165 -0.00770807 -0.09275304]
observation before action:
[-0.01991735 -0.02135165 -0.00770807 -0.09275304]
observation after action:
[-0.02034439  0.17387993 -0.00956313 -0.38785786]
observation before action:
[-0.02034439  0.17387993 -0.00956313 -0.38785786]
observation after action:
[-0.01686679  0.36913631 -0.01732028 -0.68354055]
observation before action:
[-0.01686679  0.3691363

observation before action:
[-0.04050758 -0.41990913  0.00409706  0.47374718]
observation after action:
[-0.04890576 -0.22484527  0.013572    0.18235839]
observation before action:
[-0.04890576 -0.22484527  0.013572    0.18235839]
observation after action:
[-0.05340267 -0.02992013  0.01721917 -0.10601236]
observation before action:
[-0.05340267 -0.02992013  0.01721917 -0.10601236]
observation after action:
[-0.05400107 -0.22528455  0.01509892  0.19205302]
observation before action:
[-0.05400107 -0.22528455  0.01509892  0.19205302]
observation after action:
[-0.05850676 -0.42061921  0.01893998  0.48946052]
observation before action:
[-0.05850676 -0.42061921  0.01893998  0.48946052]
observation after action:
[-0.06691915 -0.22576951  0.02872919  0.20280641]
observation before action:
[-0.06691915 -0.22576951  0.02872919  0.20280641]
observation after action:
[-0.07143454 -0.03106995  0.03278532 -0.08067718]
observation before action:
[-0.07143454 -0.03106995  0.03278532 -0.08067718]
obser

observation before action:
[-0.10726637 -0.16317403  0.10131531  0.3610159 ]
observation after action:
[-0.11052985 -0.35957919  0.10853563  0.68384866]
observation before action:
[-0.11052985 -0.35957919  0.10853563  0.68384866]
observation after action:
[-0.11772143 -0.55602742  0.1222126   1.00863395]
observation before action:
[-0.11772143 -0.55602742  0.1222126   1.00863395]
observation after action:
[-0.12884198 -0.36272998  0.14238528  0.75669153]
observation before action:
[-0.12884198 -0.36272998  0.14238528  0.75669153]
observation after action:
[-0.13609658 -0.16982751  0.15751911  0.51198597]
observation before action:
[-0.13609658 -0.16982751  0.15751911  0.51198597]
observation after action:
[-0.13949313  0.02276591  0.16775883  0.27279179]
observation before action:
[-0.13949313  0.02276591  0.16775883  0.27279179]
observation after action:
[-0.13903781 -0.17430292  0.17321467  0.61333527]
observation before action:
[-0.13903781 -0.17430292  0.17321467  0.61333527]
obser

observation before action:
[-0.21817572 -0.77504887 -0.03617782  0.26320835]
observation after action:
[-0.23367669 -0.96963625 -0.03091365  0.54426447]
observation before action:
[-0.23367669 -0.96963625 -0.03091365  0.54426447]
observation after action:
[-0.25306942 -0.77409383 -0.02002836  0.24200382]
observation before action:
[-0.25306942 -0.77409383 -0.02002836  0.24200382]
observation after action:
[-0.2685513  -0.5786916  -0.01518828 -0.05692868]
observation before action:
[-0.2685513  -0.5786916  -0.01518828 -0.05692868]
observation after action:
[-0.28012513 -0.77359252 -0.01632686  0.23092379]
observation before action:
[-0.28012513 -0.77359252 -0.01632686  0.23092379]
observation after action:
[-0.29559698 -0.96847741 -0.01170838  0.51841229]
observation before action:
[-0.29559698 -0.96847741 -0.01170838  0.51841229]
observation after action:
[-0.31496653 -1.16343258 -0.00134014  0.8073828 ]
observation before action:
[-0.31496653 -1.16343258 -0.00134014  0.8073828 ]
obser

observation before action:
[-0.04856531  0.35837023  0.04471323 -0.56159311]
observation after action:
[-0.0413979   0.16265025  0.03348137 -0.25516525]
observation before action:
[-0.0413979   0.16265025  0.03348137 -0.25516525]
observation after action:
[-0.0381449   0.35727855  0.02837806 -0.53710241]
observation before action:
[-0.0381449   0.35727855  0.02837806 -0.53710241]
observation after action:
[-0.03099932  0.16176934  0.01763601 -0.23561464]
observation before action:
[-0.03099932  0.16176934  0.01763601 -0.23561464]
observation after action:
[-0.02776394  0.35663494  0.01292372 -0.52268286]
observation before action:
[-0.02776394  0.35663494  0.01292372 -0.52268286]
observation after action:
[-0.02063124  0.55157263  0.00247006 -0.81126551]
observation before action:
[-0.02063124  0.55157263  0.00247006 -0.81126551]
observation after action:
[-0.00959979  0.35641692 -0.01375525 -0.51780665]
observation before action:
[-0.00959979  0.35641692 -0.01375525 -0.51780665]
obser

observation before action:
[ 0.17357401  0.5732448  -0.20476392 -0.98971164]
observation after action:
[ 0.1850389   0.38136424 -0.22455815 -0.76768445]
Episode finished after 22 timesteps
observation before action:
[ 0.03065219 -0.0298556   0.00290823  0.00478304]
observation after action:
[ 0.03005508 -0.22501914  0.00300389  0.29838213]
observation before action:
[ 0.03005508 -0.22501914  0.00300389  0.29838213]
observation after action:
[ 0.02555469 -0.02994014  0.00897154  0.00664809]
observation before action:
[ 0.02555469 -0.02994014  0.00897154  0.00664809]
observation after action:
[ 0.02495589  0.16505201  0.0091045  -0.28319077]
observation before action:
[ 0.02495589  0.16505201  0.0091045  -0.28319077]
observation after action:
[ 0.02825693  0.36004292  0.00344068 -0.57298833]
observation before action:
[ 0.02825693  0.36004292  0.00344068 -0.57298833]
observation after action:
[ 0.03545779  0.55511646 -0.00801908 -0.86458535]
observation before action:
[ 0.03545779  0.555

observation before action:
[ 0.04113584 -0.23185689 -0.0010889   0.3808172 ]
observation after action:
[ 0.0364987  -0.03671949  0.00652744  0.08779114]
observation before action:
[ 0.0364987  -0.03671949  0.00652744  0.08779114]
observation after action:
[ 0.03576431  0.15830829  0.00828326 -0.20282524]
observation before action:
[ 0.03576431  0.15830829  0.00828326 -0.20282524]
observation after action:
[ 0.03893047  0.3533108   0.00422676 -0.49288373]
observation before action:
[ 0.03893047  0.3533108   0.00422676 -0.49288373]
observation after action:
[ 0.04599669  0.15812949 -0.00563091 -0.19887171]
observation before action:
[ 0.04599669  0.15812949 -0.00563091 -0.19887171]
observation after action:
[ 0.04915928 -0.03691147 -0.00960835  0.09202961]
observation before action:
[ 0.04915928 -0.03691147 -0.00960835  0.09202961]
observation after action:
[ 0.04842105 -0.23189439 -0.00776776  0.38166569]
observation before action:
[ 0.04842105 -0.23189439 -0.00776776  0.38166569]
obser

observation before action:
[-0.0634688   0.403496    0.08645487 -0.39006468]
observation after action:
[-0.05539888  0.2072602   0.07865358 -0.07142428]
observation before action:
[-0.05539888  0.2072602   0.07865358 -0.07142428]
observation after action:
[-0.05125367  0.40117159  0.07722509 -0.3382918 ]
observation before action:
[-0.05125367  0.40117159  0.07722509 -0.3382918 ]
observation after action:
[-0.04323024  0.20504054  0.07045926 -0.02229043]
observation before action:
[-0.04323024  0.20504054  0.07045926 -0.02229043]
observation after action:
[-0.03912943  0.00898258  0.07001345  0.2917647 ]
observation before action:
[-0.03912943  0.00898258  0.07001345  0.2917647 ]
observation after action:
[-0.03894978  0.20304004  0.07584874  0.02195881]
observation before action:
[-0.03894978  0.20304004  0.07584874  0.02195881]
observation after action:
[-0.03488898  0.00691691  0.07628792  0.33757583]
observation before action:
[-0.03488898  0.00691691  0.07628792  0.33757583]
obser

observation before action:
[-0.05846839 -0.19043885  0.10593078  0.41920414]
observation after action:
[-0.06227716  0.0030351   0.11431486  0.1617054 ]
observation before action:
[-0.06227716  0.0030351   0.11431486  0.1617054 ]
observation after action:
[-0.06221646  0.19635073  0.11754897 -0.09284001]
observation before action:
[-0.06221646  0.19635073  0.11754897 -0.09284001]
observation after action:
[-0.05828945 -0.00024272  0.11569217  0.23449501]
observation before action:
[-0.05828945 -0.00024272  0.11569217  0.23449501]
observation after action:
[-0.0582943   0.19305253  0.12038207 -0.01957196]
observation before action:
[-0.0582943   0.19305253  0.12038207 -0.01957196]
observation after action:
[-0.05443325 -0.00357171  0.11999063  0.3085368 ]
observation before action:
[-0.05443325 -0.00357171  0.11999063  0.3085368 ]
observation after action:
[-0.05450468 -0.20018078  0.12616136  0.63652256]
observation before action:
[-0.05450468 -0.20018078  0.12616136  0.63652256]
obser

Gym은 env.step 함수를 이용해서 에이전트가 환경(environment)에 대한 행동(action)을 취하면 행동 이후에 획득한 환경에 대한 정보를 리턴(return)해주게 된다. CartPole환경에서 리턴해주는 값들은 아래와 같다.

observation은 환경에 대한 정보를 포함한 4-dimension vector로 각각 [Cart Position(카트의 위치), Cart Velocity(카트의 속도), Pole Angle(막대기의 각도), Pole Velocity At Tip(막대기 끝의 속도)]을 의미한다.
reward는 넘어지지 않을 경우 매 시간마다 1의 값을 갖는다.
done은 현재 에피소드(episode)가 끝났는지 끝나지 않았는지를 나타내는 boolean 값이다. (막대기가 쓰러지거나 카트가 중앙에서 너무 멀리 이동하면 episode를 종료(terminate)한다.

CartPole 환경에서 Agent가 취할 수 있는 행동(action_space)은 0, 1 두개의 값이다. 0은 왼쪽으로 이동, 1은 오른쪽으로 이동을 뜻한다.

# step 함수
이 선택한 action을 step함수로 보내면, 다음의 4가지 value를 return한다.

observation : 픽셀 데이터과 같은 관찰값

reward : 그 action을 하므로서 환경에서 받는 reward값

done : 에피소드가 terminal 되면 True( 목표를 달성했거나, 에이전트가 목숨을 잃었을때)

info : 환경의 정보들( 점수 등등 )

Agent는 각 time step마다 action을 선택하며 Environment과 상호작용을 한다.

이때 Environment는 Agent로부터 action을 받고 reward와 observation을 return 한다.

 

In [1]:
import gym
env=gym.make('CartPole-v0')

for i in range(20):
    observation=env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action= env.action_space.sample()
        observation, reward, done, info = env.step(action)
        
        if done:
            print("{} timestep 뒤에 에피소드가 끝났습니다.".format(t+1))
            break
                        
env.close()

[ 0.01625895 -0.00980001  0.03207029 -0.01464411]
[ 0.01606295  0.18484769  0.0317774  -0.29703848]
[ 0.0197599   0.37950257  0.02583663 -0.5795324 ]
[ 0.02734995  0.18402826  0.01424599 -0.27882367]
[ 0.03103052  0.37894411  0.00866951 -0.56697961]
[ 0.0386094   0.57394338 -0.00267008 -0.85691872]
[ 0.05008827  0.37885791 -0.01980845 -0.56507656]
[ 0.05766543  0.18401939 -0.03110998 -0.27869942]
[ 0.06134581 -0.01064526 -0.03668397  0.00401141]
[ 0.06113291  0.18498307 -0.03660374 -0.30001632]
[ 0.06483257 -0.00959855 -0.04260407 -0.01909851]
[ 0.0646406   0.18610768 -0.04298604 -0.32491327]
[ 0.06836275 -0.0083767  -0.04948431 -0.0460902 ]
[ 0.06819522  0.18741862 -0.05040611 -0.35396612]
[ 0.07194359 -0.00695171 -0.05748543 -0.07759405]
[ 0.07180456  0.18894519 -0.05903731 -0.38784544]
[ 0.07558346 -0.00529122 -0.06679422 -0.1143453 ]
[ 0.07547764  0.19072107 -0.06908113 -0.427331  ]
[ 0.07929206 -0.00335795 -0.07762775 -0.15720055]
[ 0.0792249  -0.1972876  -0.08077176  0.11001825]


[-0.05333041 -0.02750512 -0.03033443 -0.07020503]
[-0.05388051  0.1680383  -0.03173853 -0.37230217]
[-0.05051975  0.36359642 -0.03918457 -0.67482118]
[-0.04324782  0.1690403  -0.05268099 -0.39472833]
[-0.03986701 -0.0252961  -0.06057556 -0.11910919]
[-0.04037294 -0.21950019 -0.06295774  0.15386433]
[-0.04476294 -0.02353593 -0.05988046 -0.15799705]
[-0.04523366 -0.21775172 -0.0630404   0.11521016]
[-0.04958869 -0.41191641 -0.06073619  0.38735705]
[-0.05782702 -0.21598726 -0.05298905  0.07615977]
[-0.06214677 -0.02014728 -0.05146586 -0.23275937]
[-0.06254971 -0.21449753 -0.05612105  0.04325571]
[-0.06683966 -0.0186176  -0.05525593 -0.26659252]
[-0.06721201 -0.21290918 -0.06058778  0.00816308]
[-0.0714702  -0.01697301 -0.06042452 -0.30300382]
[-0.07180966  0.17895572 -0.0664846  -0.61411456]
[-0.06823054  0.37494061 -0.07876689 -0.92697449]
[-0.06073173  0.57103273 -0.09730638 -1.24333422]
[-0.04931108  0.37728479 -0.12217306 -0.98265005]
[-0.04176538  0.18399285 -0.14182606 -0.73070288]


[-0.00881456  0.779457    0.11297468 -0.8239908 ]
[ 0.00677458  0.58298595  0.09649487 -0.498019  ]
[ 0.0184343   0.7766244   0.08653449 -0.75879996]
[ 0.03396679  0.58042338  0.07135849 -0.44019025]
[ 0.04557526  0.38436792  0.06255468 -0.12589388]
[ 0.05326262  0.57854053  0.06003681 -0.39820403]
[ 0.06483343  0.38262052  0.05207272 -0.08721328]
[0.07248584 0.18679232 0.05032846 0.22143332]
[ 0.07622168  0.38116012  0.05475713 -0.05495889]
[ 0.08384489  0.57545592  0.05365795 -0.32987523]
[ 0.09535401  0.37961283  0.04706044 -0.02076551]
[ 0.10294626  0.57402939  0.04664513 -0.29823683]
[ 0.11442685  0.76845647  0.0406804  -0.57585154]
[ 0.12979598  0.57278859  0.02916337 -0.2706358 ]
[0.14125175 0.37726287 0.02375065 0.03110087]
[ 0.14879701  0.57203632  0.02437267 -0.25399486]
[ 0.16023773  0.76680194  0.01929277 -0.53889167]
[ 0.17557377  0.57141416  0.00851494 -0.24019281]
[ 0.18700206  0.76641344  0.00371108 -0.53017778]
[ 0.20233033  0.57123948 -0.00689248 -0.2363278 ]
[ 0.2137

[-0.12848778  0.335058    0.1416912  -0.27041431]
[-0.12178662  0.52790366  0.13628292 -0.51526595]
[-0.11122855  0.33115225  0.1259776  -0.18293203]
[-0.10460551  0.52426758  0.12231896 -0.43336994]
[-0.09412015  0.32764538  0.11365156 -0.10476812]
[-0.08756725  0.13109368  0.11155619  0.22149906]
[-0.08494537 -0.06543136  0.11598618  0.54718378]
[-0.086254   -0.26197544  0.12692985  0.8740426 ]
[-0.09149351 -0.45857339  0.1444107   1.2037844 ]
[-0.10066498 -0.26558283  0.16848639  0.95962118]
[-0.10597663 -0.07307718  0.18767882  0.72425258]
[-0.10743818 -0.27023029  0.20216387  1.06964344]
26 timestep 뒤에 에피소드가 끝났습니다.
[ 0.02200063  0.03591068 -0.02270898  0.02596707]
[ 0.02271885  0.23135081 -0.02218963 -0.2737934 ]
[ 0.02734586  0.42678223 -0.0276655  -0.57339158]
[ 0.03588151  0.23205887 -0.03913333 -0.28955093]
[ 0.04052269  0.42771636 -0.04492435 -0.59431474]
[ 0.04907701  0.23325105 -0.05681065 -0.31611439]
[ 0.05374203  0.03898239 -0.06313294 -0.04187486]
[ 0.05452168  0.234950

step으로 반환되는 값들은 observation은 환경에 대한 정보를 포함한 4-dimension vector로 받는다.
cart position(카트의위치), cart Velocity(카트의속도), Pole Angle(막대기의 각도), pole velocity at tip(막대기 끝의 속도)
reward는 넘어지지 않을 경우 매 시간마다 1의 값을 보상을 받음.
done은 에피소드가 terminal되면 True(목표를 달성 or 에이전트가 목숨 잃었을때)
info는 환경의 정보들(점수 등등(

행동(action_space)는 0과 1 두개의 값. 0은 왼쪽으로 이동, 1은 오른쪽으로 이동

CartPole-v0은 한 에피소드에서 얻을 수 있는 최대보상은 200step임.
매 스탭마다 막대가 넘어지지 않으면 1의 보상을 받는데
100 에피스도 연속으로 195이상의 보상(reward)를 획득하면 문제를 해결했다고 봄.


In [1]:
import gym
import numpy as np
import random

env = gym.make('CartPole-v1')
limit_step = 500

sum_score = []

from keras.models     import Sequential
from keras.models     import load_model, model_from_json
from keras.layers     import Dense
from keras.optimizers import Adam

def study_model(model, data_set):
  x_data = np.array([i[0] for i in data_set]).reshape(-1, 4)
  y_label = np.array([i[1] for i in data_set]).reshape(-1, 2)
  model.fit(x_data, y_label, epochs=2,verbose=0)

def get_predict(s):
    return np.random.choice([0, 1], p=model.predict(s.reshape(-1, 4))[0] )

#==============================================
def agent_driving(i_episode,top_cut, fun, render=False, test=False):
  work_data = []
  for i in range(i_episode):
    reward_sum = 0
    work_step = []
    obs = env.reset()
    for step in range(limit_step):
      if render: env.render()
      action = fun(obs)
      work_step.append((obs, action))
      obs, reward, done, info = env.step(action)
      reward_sum += reward
      if not test:
        if done:
          break
    work_data.append((reward_sum, work_step))
  
  work_data.sort(key=lambda s:-s[0])

  # summary for data_set
  data_set = []
  dsum = 0
  for i in range(top_cut):
    for step in work_data[i][1]:
      if step[1] == 0:  data_set.append((step[0], [1, 0]))
      else:             data_set.append((step[0], [0, 1]))
    dsum += work_data[i][0]
  sum_score.append(dsum/top_cut) 
  return data_set
#===================================


call_save_model = 0
#===================================  
if __name__ == '__main__':


  if not call_save_model :
    model = Sequential()
    model.add(Dense(128, input_dim=4, activation='relu'))
    model.add(Dense(52, activation='relu'))
    model.add(Dense(2, activation='softmax'))
    model.compile(loss='mse', optimizer=Adam())
    
    get_data = agent_driving(60, 10, lambda s: random.randrange(0, 2))
    study_model(model, get_data)

    for i in range(16):
      get_data = agent_driving(60, 10, get_predict)    
      study_model(model, get_data)

    model.save('./testm.h5')
    print("avg : %s" % (sum_score))
  else:    
    model=load_model('testm.h5')
    
  agent_driving(100, 60, get_predict, True, True)
  env.close()
#===================================


KeyboardInterrupt: 